name: Main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Kubernetes
        run: minikube start
      - name: Initialize
        run: terraform init test
      - name: Validate
        run: terraform validate test
      - name: Plan
        run: terraform plan test
      - name: Apply
        run: terraform apply test
      - name: Apply Idempotency Check
        run: terraform apply test
      - name: Destroy
        run: terraform apply test
      - name: Destroy Idempotency Check
        run: terraform apply test
